#! /bin/sh

bspc config border_width 1
bspc config window_gap          22
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc rule -a Renoise --unmanage
bspc rule -a mpv floating=true center=true
bspc rule -a Sxiv floating=true center=true
bspc rule -a qjackctl floating=true center=true
bspc rule -a Lxappearance floating=true center=true
bspc rule -a File-roller floating=true center=true
bspc rule -a floaterm floating=true center=true
bspc rule -a Oblogout floating=true center=true

bspc rule -a dwb desktop=I
bspc rule -a Calibre desktop=II
bspc rule -a qbittorrent desktop=IX
bspc rule -a qjackctl desktop=X

#bspc monitor -d i ii iii iv v vi vii viii ix x
#bspc monitor -d One Two Three Four Five Six Seven Eight Nine Ten
bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d • • • • • • • • • •

bspc desktop I --layout monocle
bspc desktop II --layout monocle

bspc config adaptative_raise true
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.05
bspc config focused_border_color "#595959"
#green#bspc config focused_border_color "#334D24"
bspc config normal_border_color "#000000"
bspc config focus_follows_pointer true

xsetroot -cursor_name left_ptr &
redshift &
#mpdnotify start &

#compton -b &
#lxpolkit &

#panel

PANEL_HEIGHT=16
PANEL_FIFO="/tmp/panel-fifo"
PANEL_FONT="DejaVu Sans Mono:size=10"

bspc config top_padding $PANEL_HEIGHT

killall bspwmstatus dzen2 bspc xtitle

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &  # Optional: for window title
bspwmstatus | dzen2 -fn "$PANEL_FONT" -h $PANEL_HEIGHT -ta l &

panel dzen2
